/* AUTO-GENERATED by snapshot.js - do not edit by hand.
   Snapshot taken: 2026-06-08T09:55:07.236Z */
window.DEMO_DATA = {
  "asOf": "08 Jun 2026",
  "budgetActual": {
    "lines": [
      {
        "name": "Revenue",
        "budget": 2658.4,
        "actual": 231.9,
        "higherIsBetter": true
      },
      {
        "name": "Cost of Sales",
        "budget": 521.4,
        "actual": 86.8,
        "higherIsBetter": false
      },
      {
        "name": "Expenses",
        "budget": 464.1,
        "actual": 109.5,
        "higherIsBetter": false
      },
      {
        "name": "Gross Profit",
        "budget": 2137,
        "actual": 145,
        "higherIsBetter": true
      },
      {
        "name": "EBITDA",
        "budget": 1672.9,
        "actual": 35.5,
        "higherIsBetter": true
      }
    ]
  },
  "budgetOverview": {
    "byUnit": [
      {
        "unit": "BUS-007",
        "budget": 1871.7
      },
      {
        "unit": "BUS-003",
        "budget": 396.6
      },
      {
        "unit": "BUS-006",
        "budget": 461.8
      },
      {
        "unit": "BUS-004",
        "budget": 93.7
      },
      {
        "unit": "TEC-004",
        "budget": 138.2
      },
      {
        "unit": "HRA-001",
        "budget": 169.2
      },
      {
        "unit": "TEC-010",
        "budget": 63.4
      },
      {
        "unit": "TEC-011",
        "budget": 37.3
      },
      {
        "unit": "TEC-012",
        "budget": 3.9
      },
      {
        "unit": "TEC-013",
        "budget": 29
      },
      {
        "unit": "TEC-014",
        "budget": 22.2
      },
      {
        "unit": "TEC-015",
        "budget": 4.3
      },
      {
        "unit": "TEC-016",
        "budget": 10
      },
      {
        "unit": "TEC-017",
        "budget": 11.8
      },
      {
        "unit": "CSO-001",
        "budget": 18.1
      },
      {
        "unit": "CSO-002",
        "budget": 119.9
      },
      {
        "unit": "CSO-003",
        "budget": 4.8
      },
      {
        "unit": "CSO-004",
        "budget": 6.9
      },
      {
        "unit": "CEO-003",
        "budget": 66
      },
      {
        "unit": "CEO-001",
        "budget": 28.9
      },
      {
        "unit": "CEO-005",
        "budget": 3
      },
      {
        "unit": "CEO-006",
        "budget": 2.3
      },
      {
        "unit": "FIN-001",
        "budget": 48.7
      },
      {
        "unit": "HRA-002",
        "budget": 15.2
      },
      {
        "unit": "HRA-003",
        "budget": 4.6
      },
      {
        "unit": "Unassigned",
        "budget": 12.2
      }
    ],
    "monthly": {
      "labels": [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun"
      ],
      "budget": [
        111.1,
        147.1,
        199,
        284.3,
        310,
        326.4
      ],
      "actual": [
        76.1,
        5.3,
        6.4,
        46.4,
        4.5,
        1.3
      ]
    },
    "utilizationYTD": [
      {
        "unit": "BUS-007",
        "used": 47,
        "budget": 1871.7
      },
      {
        "unit": "BUS-003",
        "used": 1.3,
        "budget": 396.6
      },
      {
        "unit": "BUS-006",
        "used": 5.5,
        "budget": 461.8
      },
      {
        "unit": "BUS-004",
        "used": 25.7,
        "budget": 93.7
      },
      {
        "unit": "TEC-004",
        "used": 47.4,
        "budget": 138.2
      },
      {
        "unit": "HRA-001",
        "used": 22.1,
        "budget": 169.2
      },
      {
        "unit": "TEC-010",
        "used": 69,
        "budget": 63.4
      },
      {
        "unit": "TEC-011",
        "used": 19.3,
        "budget": 37.3
      },
      {
        "unit": "TEC-012",
        "used": 3.5,
        "budget": 3.9
      },
      {
        "unit": "TEC-013",
        "used": 0,
        "budget": 29
      },
      {
        "unit": "TEC-014",
        "used": 9.5,
        "budget": 22.2
      },
      {
        "unit": "TEC-015",
        "used": 0.2,
        "budget": 4.3
      },
      {
        "unit": "TEC-016",
        "used": 11.8,
        "budget": 10
      },
      {
        "unit": "TEC-017",
        "used": 4.8,
        "budget": 11.8
      },
      {
        "unit": "CSO-001",
        "used": 9.6,
        "budget": 18.1
      },
      {
        "unit": "CSO-002",
        "used": 4,
        "budget": 119.9
      },
      {
        "unit": "CSO-003",
        "used": 3.3,
        "budget": 4.8
      },
      {
        "unit": "CSO-004",
        "used": 3.3,
        "budget": 6.9
      },
      {
        "unit": "CEO-003",
        "used": 10.4,
        "budget": 66
      },
      {
        "unit": "CEO-001",
        "used": 30.7,
        "budget": 28.9
      },
      {
        "unit": "CEO-005",
        "used": 0.7,
        "budget": 3
      },
      {
        "unit": "CEO-006",
        "used": 0,
        "budget": 2.3
      },
      {
        "unit": "FIN-001",
        "used": 28.9,
        "budget": 48.7
      },
      {
        "unit": "HRA-002",
        "used": 8,
        "budget": 15.2
      },
      {
        "unit": "HRA-003",
        "used": 4.2,
        "budget": 4.6
      },
      {
        "unit": "Unassigned",
        "used": 3.7,
        "budget": 12.2
      }
    ]
  },
  "cashflow": {
    "bankDaily": {
      "labels": [
        "29",
        "30",
        "01",
        "04",
        "06",
        "07",
        "08",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "25",
        "26",
        "28",
        "29",
        "30",
        "02",
        "03",
        "04",
        "05",
        "08"
      ],
      "balances": [
        -68.7,
        -57.2,
        -57.4,
        -58.2,
        -58.5,
        -61.1,
        -61.4,
        -61.9,
        -62.6,
        -63,
        -64.6,
        -64,
        -64,
        -64.1,
        -65.2,
        -66.1,
        -65.4,
        -66.3,
        -66.4,
        -66.4,
        -66.6,
        -84.1,
        -87.3,
        -93.3,
        -103.9,
        -104,
        -104.7,
        -138.4,
        -139.9,
        -140.2
      ]
    },
    "collectionsByBank": [
      {
        "bank": "2485",
        "amount": 231.4
      },
      {
        "bank": "2486",
        "amount": 150.5
      },
      {
        "bank": "2495",
        "amount": 50.9
      },
      {
        "bank": "2504",
        "amount": 31
      },
      {
        "bank": "2503",
        "amount": 15.5
      },
      {
        "bank": "2482",
        "amount": 12.8
      }
    ],
    "flows": {
      "collections": 672.1,
      "otherInflows": 0,
      "operatingOut": 196.4,
      "capexOut": 7.7
    },
    "debtUtilisation": {
      "used": 26.9,
      "facility": 26.9
    },
    "capexUtilisation": {
      "used": 7.7,
      "budget": 7.7
    }
  },
  "reports": {
    "ratios": [
      {
        "label": "Gross Margin",
        "value": "62.5%",
        "trend": 0
      },
      {
        "label": "EBITDA Margin",
        "value": "15.3%",
        "trend": 0
      },
      {
        "label": "Net Margin",
        "value": "7.2%",
        "trend": 0
      },
      {
        "label": "Current Ratio",
        "value": "0.80",
        "trend": 0
      },
      {
        "label": "Quick Ratio",
        "value": "0.80",
        "trend": 0
      },
      {
        "label": "Debt / Equity",
        "value": "8.65",
        "trend": 0
      }
    ],
    "pl": [
      {
        "name": "Revenue",
        "value": 231.9,
        "type": "total"
      },
      {
        "name": "Cost of Sales",
        "value": -86.8,
        "type": "neg"
      },
      {
        "name": "Gross Profit",
        "value": 145,
        "type": "subtotal"
      },
      {
        "name": "Salaries",
        "value": -25.5,
        "type": "neg"
      },
      {
        "name": "Operating Exp.",
        "value": -84,
        "type": "neg"
      },
      {
        "name": "EBITDA",
        "value": 35.5,
        "type": "subtotal"
      },
      {
        "name": "Depreciation",
        "value": -16.2,
        "type": "neg"
      },
      {
        "name": "Financial Costs",
        "value": -2.6,
        "type": "neg"
      },
      {
        "name": "Net Profit",
        "value": 16.6,
        "type": "total"
      }
    ],
    "management": [
      {
        "metric": "Revenue",
        "month": 0,
        "last": 0,
        "ytd": 231.9,
        "vsBudget": -91.3
      },
      {
        "metric": "Gross Profit",
        "month": 0,
        "last": 0,
        "ytd": 145,
        "vsBudget": -93.2
      },
      {
        "metric": "EBITDA",
        "month": 0,
        "last": 0,
        "ytd": 35.5,
        "vsBudget": -97.9
      },
      {
        "metric": "Operating Exp.",
        "month": 0,
        "last": 0,
        "ytd": 109.5,
        "vsBudget": -76.4
      },
      {
        "metric": "Net Profit",
        "month": 0,
        "last": 0,
        "ytd": 16.6,
        "vsBudget": -99
      }
    ]
  },
  "hr": {
    "total": 1537,
    "byStatus": [
      {
        "status": "Inactive",
        "count": 843
      },
      {
        "status": "Active",
        "count": 687
      },
      {
        "status": "Terminated",
        "count": 6
      },
      {
        "status": "New",
        "count": 1
      }
    ],
    "byType": [
      {
        "type": "Contract",
        "count": 677
      },
      {
        "type": "Permanent",
        "count": 559
      },
      {
        "type": "Individual Consultant",
        "count": 259
      },
      {
        "type": "Internship",
        "count": 42
      }
    ],
    "byGender": [
      {
        "gender": "Male",
        "count": 926
      },
      {
        "gender": "Female",
        "count": 606
      },
      {
        "gender": " ",
        "count": 5
      }
    ]
  }
};
